[theme]

# Primary accent for interactive elements
primaryColor = '#BD93F9'

# Background color for the main content area
backgroundColor = '#282A36'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#44475A'

# Color used for almost all text
textColor = '#F8F8F2'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
